#!/bin/sh
# /etc/init.d/minecraft
### BEGIN INIT INFO
# Provides: minecraft
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Should-Start: $network
# Should-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 6
# Short-Description: Minecraft server
# Description: Init script for minecraft/bukkit server, with rolling logs and use of ramdisk for less lag.
### END INIT INFO

SESSION_NAME=minecraft
USER_NAME=minecraft
MC_PATH=/home/minecraft
#COMMAND="sh ServerStart.sh"
COMMAND="sh start.sh"
PID_FILE="$MC_PATH/server.pid"

[ `id -u` = 0 ] && exec sudo -u $USER_NAME $0 "$@"

check_user() {
	[ `whoami` != $USER_NAME ] && {
		echo Permission denied
		exit 1
	}
}

#set PID

is_running() {
	if [ -f $PID_FILE ]; then
		PID=`cat $PID_FILE`
		[ -n "$PID" ] && [ "$PID" != 0 ] && [ -d "/proc/$PID" ] && return 0
	fi
	rm -f $PID_FILE
	return 1
}

mc_start() {
	check_user
	if is_running; then
		echo already running
		exit 1
	fi
	#echo Starting Minecraft server...
	cd "$MC_PATH"
	tmux -L "$SESSION_NAME" new-session -d "$COMMAND"
	sleep 1
	if is_running; then
		echo Minecraft server started
	else
		echo Failed to start Minecraft server
		exit 1
	fi
}

mc_stop() {
	check_user
	if ! is_running; then
		echo Serivce is not running
		exit 1
	fi
	#echo Stopping Minecraft server...
	tmux -L "$SESSION_NAME" send-keys -t 0 C-u stop ENTER
	#sleep 4
	for i in 1 2 3 4; do
		sleep 1
		printf .
		if ! is_running; then
			echo Stopped
			return 0
		fi
	done
	echo
	#if is_running; then
		echo Sending SIGINT...
		kill -s INT $PID
		sleep 2
		if is_running; then
			echo Sending SIGTERM...
			kill $PID
			sleep 1
			if is_running; then
				echo Sending SIGKILL...
				kill -s KILL $PID
			fi
		fi
	#fi
	echo Stopped
}

case "$1" in
	start)
		mc_start
		;;
	stop)
		mc_stop
		;;
	restart)
		mc_stop
		sleep 0.5
		mc_start
		;;
	status)
		if is_running; then
			echo "Running (pid $PID)"
			exit 0
		else
			echo "Not running"
			exit 1
		fi
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 255
		;;
esac
exit 0

